name: Sync Directories
on:
  push:
    branches:
      - master
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub File Sync
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |
            \.md$
          TARGET_REPOS: |
            groupdocs/DestRepoGD:master
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          SRC_ROOT: /Groupdocs.Blog/
          TARGET_ROOT: /content/Groupdocs.Blog/